controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    axlr_controller:
      type: velocity_controllers/JointGroupVelocityController

    axlr_ros_controller:
      type: diff_drive_controller/DiffDriveController

axlr_controller:
  ros__parameters:
    joints:
      - right_wheel_joint
      - left_wheel_joint


axlr_ros_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: true
    left_wheel_names: [left_wheel_joint]
    right_wheel_names: [right_wheel_joint]
    publish_rate: 50.0
    pose_covariance_diagonal: [0.001,0.001,1.0e-3,1.0e-3,0.01]
    twist_covariance_diagonal: [0.001,0.001,1.0e-3,1.0e-3,0.01]

    wheel_radius: 0.042
    wheel_separation: 0.316
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    wheel_separation_multiplier: 1.0
    cmd_vel_timeout: 0.25
    base_frame_id: base_link
    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: true

    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 2.0  # m/s
        min_velocity           : -1.0 # m/s
        has_acceleration_limits: true
        max_acceleration       : 1.5  # m/s^2
        min_acceleration       : -0.75 # m/s^2
        has_jerk_limits        : false
        max_jerk               : 5.0  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.57  # rad/s
        has_acceleration_limits: true
        max_acceleration       : 1.57  # rad/s^2
        has_jerk_limits        : false
        max_jerk               : 2.5  # rad/s^3

        