controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    axlr_controller:
      type: velocity_controllers/JointGroupVelocityController

axlr_controller:
  ros__parameters:
    joints:
      - base_right_wheel
      - base_left_wheel