<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <link name="world"/>
    <link name="base_link">
        <visual>
            <origin xyz="${-center_offset} 0.0 ${base_height/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_width} ${base_length} ${base_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${-center_offset} 0.0 ${base_height/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_width} ${base_length} ${base_height}"/>
            </geometry>
            <material name="white"/>
        </collision>
        <xacro:box_inertia m="1.0" l="${base_width}" w="${base_length}" h="${base_height}"
                xyz="${-center_offset} 0.0 ${base_height/2}" rpy="0.0 0.0 0.0"/>
    </link>

    <joint name="world_joint" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
        <origin xyz="${center_offset} 0.0 ${wheel_diameter/2}" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="right_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </collision>
        <xacro:cylinder_inertia m="0.1" r ="${wheel_diameter/2}" h="${wheel_length}"
             xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </link>

    <joint name="right_wheel_joint" type="continuous">
        <origin xyz="0.0 -${base_length/2 + wheel_offset_from_side} 0.0" rpy="${PI/2} 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <axis xyz="0.0 0.0 -1.0"/>
    </joint>

    <link name="left_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </collision>
        <xacro:cylinder_inertia m="0.1" r ="${wheel_diameter/2}" h="${wheel_length}"
             xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </link>

    <joint name="left_wheel_joint" type="continuous">
        <origin xyz="0.0 ${base_length/2 + wheel_offset_from_side} 0.0" rpy="${PI/2} 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <axis xyz="0.0 0.0 -1.0"/>
    </joint>

    <link name="caster_wheel_link">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${wheel_diameter/4}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <sphere radius="${wheel_diameter/4}"/>
            </geometry>
            <material name="black"/>
        </collision>
        <xacro:sphere_inertia m="0.1" r ="${wheel_diameter/4}"
                xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </link>
    <joint name="caster_joint" type="fixed">
        <origin xyz="-${base_width/2} 0.0 -${wheel_diameter/4}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
    </joint>

</robot>