<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_length" value="0.266"/>
    <xacro:property name="base_width" value="0.237"/>
    <xacro:property name="base_height" value="0.122"/>
    <xacro:property name="wheel_offset_from_ground" value="0.072"/>
    <xacro:property name="wheel_offset_from_width" value="0.0325"/>
    <xacro:property name="wheel_offset_from_side" value="0.025"/>
    <xacro:property name="wheel_offset_from_top" value="0.03"/>
    <xacro:property name="caster_wheel_radius" value="0.015"/>
    <xacro:property name="caster_wheel_offset_from_top" value="0.03"/>
    <xacro:property name="wheel_diameter" value="0.084"/>
    <xacro:property name="wheel_length" value="0.04"/>
    <xacro:property name="PI" value="3.14159"/>
    <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>
    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>
    <link name="world">
        
    </link>
    <link name="base_link">
        <visual>
            <origin xyz="0.0 ${-wheel_offset_from_width} ${base_height/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0.0 ${-wheel_offset_from_width} ${base_height/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="white"/>
        </collision>
    </link>

    <joint name="world_base" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
        <origin xyz="0.0 ${wheel_offset_from_width} ${wheel_offset_from_ground}" rpy="0.0 0.0 0.0"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </collision>
    </link>

    <joint name="base_right_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="${base_length/2+wheel_offset_from_side} 0.0 ${-wheel_offset_from_top}" rpy="0.0 ${PI/2} 0.0"/>
        <axis xyz="0.0 0.0 1.0"/>
    </joint>
    <link name="left_wheel">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </collision>
    </link>

    <joint name="base_left_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="-${base_length/2+wheel_offset_from_side} 0.0 ${-wheel_offset_from_top}" rpy="0.0 ${-PI/2} 0.0"/>
        <axis xyz="0.0 0.0 1.0"/>
    </joint>

    <link name="back_support">
        <visual>
            <origin xyz="0.0 0.0 -0.03" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.02 0.02 0.06"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 -0.03" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.02 0.02 -0.06"/>
            </geometry>
            <material name="black"/>
        </collision>
    </link>

    <joint name="base_back_support" type="fixed">
        <parent link="base_link"/>
        <child link="back_support"/>
        <origin xyz="0.0 -${base_width/2+wheel_offset_from_width-0.02} 0.0" rpy="0.0 0.0 0.0"/>
    </joint>


    <link name="base_caster_wheel">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </collision>
    </link>
    <joint name="base_caster_wheel" type="fixed">
        <parent link="back_support"/>
        <child link="base_caster_wheel"/>
        <origin xyz="0.0 0.0 -0.06" rpy="0.0 0.0 0.0"/>
    </joint>
</robot>