<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <link name="world"/>
    <link name="base_link">
        <visual>
            <origin xyz="0.0 ${-wheel_offset_from_width} ${base_height/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0.0 ${-wheel_offset_from_width} ${base_height/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name="white"/>
        </collision>
        <xacro:box_inertia  m="2.5" l="${base_length}" w="${base_width}" h="${base_height}"
            xyz="0.0 ${-wheel_offset_from_width} ${base_height/2}" rpy="0.0 0.0 0.0"/>
    </link>

    <joint name="world_base" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
        <origin xyz="0.0 ${wheel_offset_from_width} ${wheel_offset_from_ground}" rpy="0.0 0.0 ${-PI/2}"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </collision>
        <xacro:cylinder_inertia m="0.1" r="${wheel_diameter/2}" h="${wheel_length}"
                xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </link>

    <joint name="base_right_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="${base_length/2+wheel_offset_from_side} 0.0 ${-wheel_offset_from_top}" rpy="0.0 ${PI/2} 0.0"/>
        <axis xyz="0.0 0.0 1.0"/>
    </joint>
    <link name="left_wheel">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_length}"/>
            </geometry>
            <material name="black"/>
        </collision>
        <xacro:cylinder_inertia m="0.1" r="${wheel_diameter/2}" h="${wheel_length}"
                xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </link>

    <joint name="base_left_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="-${base_length/2+wheel_offset_from_side} 0.0 ${-wheel_offset_from_top}" rpy="0.0 ${-PI/2} 0.0"/>
        <axis xyz="0.0 0.0 1.0"/>
    </joint>

    <link name="back_support">
        <visual>
            <origin xyz="0.0 0.0 -0.03" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.02 0.02 0.06"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 -0.03" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.02 0.02 -0.06"/>
            </geometry>
            <material name="black"/>
        </collision>
        <xacro:box_inertia  m="0.2" l="0.02" w="0.02" h="0.06"
                xyz="0.0 0.0 -0.03" rpy="0.0 0.0 0.0"/>
    </link>

    <joint name="base_back_support" type="fixed">
        <parent link="base_link"/>
        <child link="back_support"/>
        <origin xyz="0.0 -${base_width/2+wheel_offset_from_width-0.02} 0.0" rpy="0.0 0.0 0.0"/>
    </joint>


    <link name="base_caster_wheel">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </collision>
        <xacro:sphere_inertia m="0.2" r="${caster_wheel_radius}"
                xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </link>
    <joint name="base_caster_wheel" type="fixed">
        <parent link="back_support"/>
        <child link="base_caster_wheel"/>
        <origin xyz="0.0 0.0 -0.06" rpy="0.0 0.0 0.0"/>
    </joint>
</robot>